// Mock data constants for PYMSTR application
// Extracted from App.tsx to reduce file size and improve maintainability

export const INITIAL_PAYMENT_LINKS = [
  {
    id: "1",
    linkId: "#PL001",
    price: 250,
    baseCurrency: "USD",
    description: "Consulting Services",
    status: "completed",
    source: "manual",
    chain: "ethereum",
    currency: "USDC",
    availableCurrencies: ["USDC", "USDT", "EURC"],
    availableChains: ["ethereum", "polygon"],
    txHash: "0x7f3a8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f",
  },
  {
    id: "2",
    linkId: "#PL002",
    price: 89.99,
    baseCurrency: "EUR",
    description: "Digital Product",
    status: "expired",
    source: "api",
    chain: "polygon",
    currency: "USDT",
    availableCurrencies: ["USDT"],
    availableChains: ["polygon"],
  },
  {
    id: "3",
    linkId: "#PL003",
    price: 150,
    baseCurrency: "USD",
    description: "Monthly Subscription",
    status: "active",
    source: "manual",
    expiryDate: "2025-12-31",
    chain: "arbitrum",
    currency: "USDC",
    availableCurrencies: ["USDC", "EURC"],
    availableChains: ["arbitrum", "optimism"],
  },
  {
    id: "4",
    linkId: "#PL004",
    price: 75.5,
    baseCurrency: "EUR",
    description: "API Generated Link",
    status: "active",
    source: "api",
    chain: "optimism",
    currency: "EURC",
    availableCurrencies: ["EURC", "USDC"],
    availableChains: ["optimism"],
  },
  {
    id: "5",
    linkId: "#PL005",
    price: 199.99,
    baseCurrency: "USD",
    description: "Premium Service",
    status: "active",
    source: "manual",
    expiryDate: "2025-11-15",
    chain: "ethereum",
    currency: "USDC",
    availableCurrencies: ["USDC", "USDT", "EURC"],
    availableChains: ["ethereum", "polygon", "arbitrum"],
  },
  {
    id: "6",
    linkId: "#PL006",
    price: 45.0,
    baseCurrency: "AED",
    description: "E-book Download",
    status: "completed",
    source: "api",
    expiryDate: "2025-10-20",
    chain: "polygon",
    currency: "USDT",
    availableCurrencies: ["USDT", "USDC"],
    availableChains: ["polygon", "ethereum"],
    txHash: "0xa4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f",
  },
  {
    id: "7",
    linkId: "#PL007",
    price: 299.5,
    baseCurrency: "EUR",
    description: "Annual License",
    status: "active",
    source: "manual",
    chain: "arbitrum",
    currency: "EURC",
    availableCurrencies: ["EURC"],
    availableChains: ["arbitrum", "optimism"],
  },
  {
    id: "8",
    linkId: "#PL008",
    price: 12.99,
    baseCurrency: "JPY",
    description: "Monthly Plan",
    status: "inactive",
    source: "api",
    chain: "optimism",
    currency: "USDC",
    availableCurrencies: ["USDC"],
    availableChains: ["optimism"],
  },
  {
    id: "9",
    linkId: "#PL009",
    price: 500,
    baseCurrency: "USD",
    description: "Enterprise Setup",
    status: "active",
    source: "manual",
    expiryDate: "2025-12-01",
    chain: "ethereum",
    currency: "USDT",
    availableCurrencies: ["USDC", "USDT", "EURC"],
    availableChains: ["ethereum", "polygon", "arbitrum", "optimism", "base"],
  },
  {
    id: "10",
    linkId: "#PL010",
    price: 25.0,
    baseCurrency: "AED",
    description: "Basic Package",
    status: "completed",
    source: "api",
    chain: "polygon",
    currency: "USDC",
    availableCurrencies: ["USDC"],
    availableChains: ["polygon"],
    txHash: "0x8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b",
  },
  {
    id: "11",
    linkId: "#PL011",
    price: 175.75,
    baseCurrency: "EUR",
    description: "Design Services",
    status: "active",
    source: "manual",
    expiryDate: "2025-10-25",
    chain: "arbitrum",
    currency: "USDC",
    availableCurrencies: ["USDC", "USDT"],
    availableChains: ["arbitrum", "polygon"],
  },
  {
    id: "12",
    linkId: "#PL012",
    price: 99.99,
    baseCurrency: "EUR",
    description: "Pro Subscription",
    status: "expired",
    source: "api",
    expiryDate: "2025-09-30",
    chain: "optimism",
    currency: "EURC",
    availableCurrencies: ["EURC"],
    availableChains: ["optimism", "arbitrum"],
  },
  {
    id: "13",
    linkId: "#PL013",
    price: 350,
    baseCurrency: "USD",
    description: "Custom Development",
    status: "active",
    source: "manual",
    chain: "base",
    currency: "USDC",
    availableCurrencies: ["USDC", "USDT"],
    availableChains: ["base", "polygon"],
  },
  {
    id: "14",
    linkId: "#PL014",
    price: 59.99,
    baseCurrency: "USD",
    description: "Plugin License",
    status: "active",
    source: "api",
    expiryDate: "2025-11-30",
    chain: "polygon",
    currency: "USDT",
    availableCurrencies: ["USDT"],
    availableChains: ["polygon", "ethereum"],
  },
  {
    id: "15",
    linkId: "#PL015",
    price: 125,
    baseCurrency: "JPY",
    description: "Training Session",
    status: "inactive",
    source: "manual",
    chain: "arbitrum",
    currency: "USDC",
    availableCurrencies: ["USDC", "EURC"],
    availableChains: ["arbitrum"],
  },
  {
    id: "16",
    linkId: "#PL016",
    price: 19.99,
    baseCurrency: "USD",
    description: "Mobile App",
    status: "active",
    source: "api",
    expiryDate: "2025-10-15",
    chain: "optimism",
    currency: "USDC",
    availableCurrencies: ["USDC", "USDT", "EURC"],
    availableChains: ["optimism", "polygon", "arbitrum"],
  },
  {
    id: "17",
    linkId: "#PL017",
    price: 750,
    baseCurrency: "EUR",
    description: "Full Website",
    status: "active",
    source: "manual",
    chain: "ethereum",
    currency: "EURC",
    availableCurrencies: ["EURC", "USDC"],
    availableChains: ["ethereum"],
  },
  {
    id: "18",
    linkId: "#PL018",
    price: 39.99,
    baseCurrency: "USD",
    description: "Theme Package",
    status: "active",
    source: "api",
    chain: "polygon",
    currency: "USDC",
    availableCurrencies: ["USDC", "USDT"],
    availableChains: ["polygon"],
  },
  {
    id: "19",
    linkId: "#PL019",
    price: 225,
    baseCurrency: "AED",
    description: "SEO Audit",
    status: "active",
    source: "manual",
    chain: "arbitrum",
    currency: "USDT",
    expiryDate: "2025-11-10",
    availableCurrencies: ["USDT", "USDC"],
    availableChains: ["arbitrum", "ethereum"],
  },
  {
    id: "20",
    linkId: "#PL020",
    price: 8.99,
    baseCurrency: "JPY",
    description: "Stock Photos",
    status: "expired",
    source: "api",
    expiryDate: "2025-09-15",
    chain: "optimism",
    currency: "EURC",
    availableCurrencies: ["EURC"],
    availableChains: ["optimism"],
  },
];

export const INITIAL_WALLETS = [
  {
    id: "1",
    name: "Main Wallet",
    address: "0x742d35cc6af4b1e2b6b265c3e2f3b4d123456789",
    balance: {
      USDC: 1245.67,
      USDT: 890.23,
      EURC: 567.89,
    },
    chainBalances: {
      USDC: {
        ethereum: 450.23,
        polygon: 320.15,
        arbitrum: 275.89,
        optimism: 199.40,
      },
      USDT: {
        ethereum: 320.50,
        polygon: 245.73,
        arbitrum: 180.00,
        optimism: 144.00,
      },
      EURC: {
        ethereum: 200.45,
        polygon: 150.22,
        arbitrum: 120.12,
        optimism: 97.10,
      },
    },
    isDefault: true,
    emailNotifications: true,
  },
  {
    id: "2",
    name: "Business Wallet",
    address: "0x8f3e4a5b7c9d1e2f3a4b5c6d7e8f9a0b1c2d3e4f",
    balance: {
      USDC: 456.78,
      USDT: 123.45,
      EURC: 789.01,
    },
    chainBalances: {
      USDC: {
        ethereum: 200.00,
        polygon: 100.50,
        arbitrum: 90.28,
        optimism: 66.00,
      },
      USDT: {
        ethereum: 50.00,
        polygon: 30.45,
        arbitrum: 23.00,
        optimism: 20.00,
      },
      EURC: {
        ethereum: 350.00,
        polygon: 200.01,
        arbitrum: 150.00,
        optimism: 89.00,
      },
    },
    isDefault: false,
    emailNotifications: true,
  },
  {
    id: "3",
    name: "Savings Wallet",
    address: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    balance: {
      USDC: 2890.45,
      USDT: 1567.23,
      EURC: 934.12,
    },
    chainBalances: {
      USDC: {
        ethereum: 1200.00,
        polygon: 800.45,
        arbitrum: 550.00,
        optimism: 340.00,
      },
      USDT: {
        ethereum: 700.00,
        polygon: 400.23,
        arbitrum: 300.00,
        optimism: 167.00,
      },
      EURC: {
        ethereum: 400.00,
        polygon: 250.12,
        arbitrum: 184.00,
        optimism: 100.00,
      },
    },
    isDefault: false,
    emailNotifications: false,
  },
];

export const INITIAL_TEAM_MEMBERS = [
  {
    id: "1",
    name: "John Admin",
    email: "john@pymstr.com",
    role: "admin",
    status: "active",
    avatar: "JA",
    lastActive: "2025-10-05T10:30:00Z",
  },
  {
    id: "2",
    name: "Sarah Manager",
    email: "sarah@pymstr.com",
    role: "admin",
    status: "active",
    avatar: "SM",
    lastActive: "2025-10-05T08:15:00Z",
  },
  {
    id: "3",
    name: "Mike Viewer",
    email: "mike@pymstr.com",
    role: "view-only",
    status: "active",
    avatar: "MV",
    lastActive: "2025-10-04T16:45:00Z",
  },
  {
    id: "5",
    name: "Alex Pending",
    email: "alex@pymstr.com",
    role: "view-only",
    status: "pending",
    avatar: "AP",
    lastActive: "Never",
  },
];

export const INITIAL_API_KEYS = [
  {
    id: "1",
    name: "Production - Main Website",
    key: "pk_live_a7f3d9e2b4c8h1k5m9n2p6q8t3v7w1x4",
    environment: "live",
    status: "active",
    createdAt: "2025-10-05T10:30:00Z",
    lastUsed: "2025-10-09T08:15:00Z",
    totalCalls: 15234,
    permissions: [
      "read_payments",
      "create_payment_links",
      "receive_webhooks",
    ],
    ipWhitelist: ["192.168.1.1", "10.0.0.5"],
    rateLimit: { perMinute: 100, perHour: 1000 },
  },
  {
    id: "2",
    name: "Test - Development",
    key: "pk_test_x9y8z7w6v5u4t3s2r1q0p9o8n7m6l5k4",
    environment: "test",
    status: "active",
    createdAt: "2025-09-20T14:20:00Z",
    lastUsed: "2025-10-08T16:45:00Z",
    totalCalls: 8923,
    permissions: ["read_payments", "create_payment_links"],
    ipWhitelist: [],
    rateLimit: { perMinute: 100, perHour: 1000 },
  },
  {
    id: "3",
    name: "Mobile App - iOS",
    key: "pk_live_m5n4b3v2c1x0z9y8w7v6u5t4s3r2q1p0",
    environment: "live",
    status: "inactive",
    createdAt: "2025-08-12T09:10:00Z",
    lastUsed: null,
    totalCalls: 0,
    permissions: ["read_payments"],
    ipWhitelist: [],
    rateLimit: { perMinute: 100, perHour: 1000 },
  },
];

export const DASHBOARD_STATS = {
  // Tier 1 - Essential
  totalVolumeProcessed: 125847.32,
  successfulTransactions: 1847,
  successRate: 96.8,
  averageTransactionValue: 68.14,
  totalFeesEarned: 3649.77, // Total fees earned by merchant
  
  // Tier 2 - Important Secondary
  activePayors: 342,
  failedTransactions: 61,
  settlementSpeed: 45, // seconds
  
  // Tier 3 - Web3 Specific
  gasFeesSaved: 892.45,
  multiChainVolume: {
    ethereum: 67234.12,
    polygon: 32456.89,
    arbitrum: 18934.56,
    optimism: 7221.75,
    base: 15892.34,
  },
  currencyVolume: {
    USDC: 68542.34,
    USDT: 42156.78,
    EURC: 12847.12,
  },
};

export const RECENT_TRANSACTIONS = [
  {
    id: "1",
    linkId: "#PL001",
    price: "156.78",
    baseCurrency: "USD",
    crypto: "USDC",
    cryptoAmount: "156.78", // USDC amount paid
    status: "Success",
    date: "2025-09-30T10:30:00Z",
    chain: "ethereum",
    txHash: "0x7f3a8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f",
    fee: "4.70", // 3% fee in USDC
    received: "152.08", // USDC received after fee
  },
  {
    id: "2",
    linkId: "#PL002",
    price: "89.50",
    baseCurrency: "EUR",
    crypto: "USDT",
    cryptoAmount: "89.50", // USDT amount paid
    status: "Pending",
    date: "2025-09-30T09:15:00Z",
    chain: "polygon",
    txHash: "0xa4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f",
    fee: "2.69", // 3% fee in USDT
    received: "86.81", // USDT received
  },
  {
    id: "3",
    linkId: "#PL003",
    price: "234.12",
    baseCurrency: "AED",
    crypto: "USDC",
    cryptoAmount: "234.12", // USDC amount paid
    status: "Fail",
    date: "2025-09-30T08:45:00Z",
    chain: "arbitrum",
    txHash: "0x1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f",
    fee: "7.02", // 3% fee in USDC
    received: "227.10", // USDC received
  },
  {
    id: "4",
    linkId: "#PL004",
    price: "67.89",
    baseCurrency: "USD",
    crypto: "EURC",
    cryptoAmount: "67.89", // EURC amount paid
    status: "Success",
    date: "2025-09-30T07:20:00Z",
    chain: "optimism",
    txHash: "0x8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b2c5d1a4f8e9b",
    fee: "2.04", // 3% fee in EURC
    received: "65.85", // EURC received
  },
];

export const CHART_DATA = [
  { month: "Jan", transactions: 145, revenue: 12456 },
  { month: "Feb", transactions: 178, revenue: 15234 },
  { month: "Mar", transactions: 234, revenue: 18967 },
  { month: "Apr", transactions: 289, revenue: 23145 },
  { month: "May", transactions: 312, revenue: 26789 },
  { month: "Jun", transactions: 345, revenue: 29456 },
];

export const INITIAL_MERCHANT_CONFIG = {
  merchantId: "MERCH123",
  acceptedPayments: [
    { token: "USDC", chains: ["ethereum", "polygon", "arbitrum", "optimism", "base"] },
    { token: "USDT", chains: ["ethereum", "polygon", "arbitrum", "optimism", "base"] },
    { token: "EURC", chains: ["ethereum", "polygon", "arbitrum", "optimism", "base"] },
  ],
};

export const INITIAL_NEW_MEMBER = {
  name: "",
  email: "",
  role: "view-only",
};

export const INITIAL_NEW_API_KEY = {
  name: "",
  environment: "test",
  permissions: ["read_payments"],
  ipWhitelist: "",
  autoExpire: false,
  expiryDays: 90,
};